import { z } from "zod";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { adminProcedure, publicProcedure, router } from "./_core/trpc";
import { addAdmin, changeAdminPassword, createGame, createNotice, createTeam, deleteGame, deleteNotice, deleteTeam, getNotice, getSettings, listAllTeam, listGames, listNotices, listTeam, saveSettings, updateGame, updateNotice, updateTeam } from "./db";
import { hash } from "bcryptjs";
const fallbackNotices = [{ id: "fallback-1", category: "STUDIO", title: "라믹 스튜디오가 새로운 세계를 만들기 시작했습니다.", body: "데이터베이스 연결을 기다리는 중입니다.", publishedAt: new Date("2026-09-18") }];
const gameInput = z.object({ code: z.string().min(1).max(20), title: z.string().min(1).max(120), description: z.string().max(2000).default(""), genre: z.string().max(120).default(""), status: z.string().max(80).default("개발 중"), imageUrl: z.string().max(2000).default(""), videoUrl: z.string().max(2000).nullable().optional(), externalUrl: z.string().url().max(2000).nullable().optional(), externalLabel: z.string().max(40).nullable().optional(), isNew: z.boolean().default(false), previewUrl: z.string().max(2000).nullable().optional() });
export const appRouter = router({ system: systemRouter, auth: router({ me: publicProcedure.query(opts => opts.ctx.user), logout: publicProcedure.mutation(({ ctx }) => { ctx.res.clearCookie(COOKIE_NAME, { ...getSessionCookieOptions(ctx.req), maxAge: -1 }); return { success: true } as const; }) }),
  site: router({ settings: publicProcedure.query(() => getSettings()), games: publicProcedure.query(async () => listGames()), team: publicProcedure.query(async () => listTeam()) }),
  news: router({ list: publicProcedure.query(async () => { const rows = await listNotices(); return rows.length ? rows : fallbackNotices; }), detail: publicProcedure.input(z.object({ id: z.string() })).query(({ input }) => getNotice(input.id)), publish: adminProcedure.input(z.object({ category: z.string().min(1).max(40), title: z.string().min(3).max(255), body: z.string().min(3).max(100000), coverUrl: z.string().max(2000).nullable().optional(), publishedAt: z.date().optional() })).mutation(({ input }) => createNotice({ ...input, publishedAt: input.publishedAt ?? new Date() })), update: adminProcedure.input(z.object({ id: z.string(), category: z.string().min(1).max(40), title: z.string().min(3).max(255), body: z.string().min(3).max(100000), coverUrl: z.string().max(2000).nullable().optional(), publishedAt: z.date().optional() })).mutation(({ input }) => updateNotice(input.id, input)), remove: adminProcedure.input(z.object({ id: z.string() })).mutation(({ input }) => deleteNotice(input.id)) }),
  admin: router({ notices: adminProcedure.query(() => listNotices()), games: adminProcedure.query(() => listGames()), team: adminProcedure.query(() => listAllTeam()), createGame: adminProcedure.input(gameInput).mutation(({ input }) => createGame(input)), updateGame: adminProcedure.input(gameInput.extend({ id: z.string() })).mutation(({ input }) => { const { id, ...game } = input; return updateGame(id, game); }), deleteGame: adminProcedure.input(z.object({ id: z.string() })).mutation(({ input }) => deleteGame(input.id)), createTeam: adminProcedure.input(z.object({ name: z.string().min(1).max(120), role: z.string().min(1).max(120), bio: z.string().max(2000).default(""), imageUrl: z.string().max(2000).nullable().optional(), sortOrder: z.number().int().min(0).default(0), isPublic: z.boolean().default(true) })).mutation(({ input }) => createTeam(input)), updateTeam: adminProcedure.input(z.object({ id: z.string(), name: z.string().min(1).max(120), role: z.string().min(1).max(120), bio: z.string().max(2000).default(""), imageUrl: z.string().max(2000).nullable().optional(), sortOrder: z.number().int().min(0).default(0), isPublic: z.boolean().default(true) })).mutation(({ input }) => { const { id, ...member } = input; return updateTeam(id, member); }), deleteTeam: adminProcedure.input(z.object({ id: z.string() })).mutation(({ input }) => deleteTeam(input.id)), saveSettings: adminProcedure.input(z.object({ logoUrl: z.string().max(2000).optional(), instagramUrl: z.string().max(2000).optional(), youtubeUrl: z.string().max(2000).optional(), discordUrl: z.string().max(2000).optional(), steamUrl: z.string().max(2000).optional(), footerText: z.string().max(500).optional() })).mutation(({ input }) => saveSettings(input)), addAdmin: adminProcedure.input(z.object({ username: z.string().min(3).max(60).regex(/^[a-zA-Z0-9._-]+$/), password: z.string().min(12).max(200), name: z.string().min(1).max(120) })).mutation(async ({ input }) => { await addAdmin(input.username, await hash(input.password, 12), input.name); return { success: true }; }), changePassword: adminProcedure.input(z.object({ password: z.string().min(12).max(200) })).mutation(async ({ ctx, input }) => { if (!ctx.user) throw new Error("관리자 인증이 필요합니다."); await changeAdminPassword((ctx.user as any).openId.replace(/^admin:/, ""), await hash(input.password, 12)); return { success: true }; }) }) });
export type AppRouter = typeof appRouter;
